<a href="https://colab.research.google.com/github/rodolfostark/Machine-learning/blob/master/MLPColorSensorClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importando as bibliotecas e iniciando as variaveis com o caminho do dataset
import numpy as np
import os
import tarfile
from six.moves import urllib
import csv

FILE_TO_DOWNLOAD =  "objetosECores.csv"
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/rodolfostark/ColorSensorMachineLearning/"
DATA_PATH = "master/"
DATA_URL = DOWNLOAD_ROOT + DATA_PATH + FILE_TO_DOWNLOAD

In [24]:
# Função que faz o download dos dados
def fetch_data(data_url=DATA_URL, data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  if not os.path.isdir(data_path):
    os.makedirs(data_path)
  urllib.request.urlretrieve(data_url, data_path+file_to_download)
  
fetch_data()
!ls master

objetosECores.csv


In [0]:
# Prepadando os dados
leitura = csv.reader(open('master/objetosECores.csv','r'))
leitura = list(leitura)

objetos_coloridos = list()
y = list()

for l in range(1, len(leitura)):
  y.append(int(leitura[l][3]) + 1)

for i in range(1, len(leitura)):
  objetos_coloridos.append(leitura[i])
  
for j in range(0, len(objetos_coloridos)):
  objetos_coloridos[j].pop()
  for k in range(0, len(objetos_coloridos[j])):
    objetos_coloridos[j][k] = float(objetos_coloridos[j][k]) 
    
Y = np.array(y)
X = np.array(objetos_coloridos)

In [0]:
# Separando subconjuntos para treino e teste
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [27]:
# Importado classificador
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15,), random_state=1)
clf.fit(X_train, y_train)
clf.predict(X_test)

array([2, 1, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 1])

In [28]:
#importando matrix de confusão
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[4 0 0]
 [0 6 0]
 [0 0 4]]
